name:                kademlia
version:             0.1.0.0
github:              "githubuser/kademlia"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/kademlia#readme>

dependencies:
- base >= 4.7 && < 5
- configurator >= 0.3.0.0
- network
- random
- async
- bytestring
- text
- split >= 0.1.2.3
- containers
- stm
- random  
- serialise
- time 
- cryptonite 
- bytes 
- raaz 
- memory 
- base16-bytestring 
- crypto-api 
- integer-gmp

library:
  source-dirs: src
  
executables:
  kademlia-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kademlia

tests:
  kademlia-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kademlia
