resolver: lts-11.11
allow-newer: true
packages:
- .
- location: ../utils
  extra-dep: true
- location: ../p2p
  extra-dep: true
- location: ../network
  extra-dep: true
- location: ../crypto
  extra-dep: true

extra-deps:
- serialise-0.2.0.0
- cborg-0.2.0.0
- statsd-client-0.3.0.0
- time-units-1.0.0
- timers-updatable-0.2.0.2
- digest-pure-0.0.3
