<<<<<<< HEAD
resolver: lts-11.11
allow-newer: true
packages:
- .
- location: ../crypto
  extra-dep: true
- location: ../utils
  extra-dep: true
=======
resolver: lts-12.26
allow-newer: true

packages:
    - .
    - ../crypto
    - ../utils
>>>>>>> breaking out arivi-core from arivi

extra-deps:
- serialise-0.2.0.0
- cborg-0.2.0.0
- timers-updatable-0.2.0.2
- statsd-client-0.3.0.0
- time-units-1.0.0
<<<<<<< HEAD
- digest-pure-0.0.3
=======
- digest-pure-0.0.3
- DRBG-0.5.5
- stm-containers-1.0.1
- either-unwrap-1.1
- raaz-0.2.1
>>>>>>> breaking out arivi-core from arivi
